version: "3"

services:
  dind:
    image: opvolger/dind:latest
    privileged: true
    container_name: "dind"
    ports:
      - "10022:22"
    networks:
      default:
        aliases:
          - "dind"
    environment:
      USER: "dind"
      PASSWORD: "dind"

